export const productData = {
  "categories": [
  {
    "id": 1,
    "name": "Fruits",
    "categoryIcon": "fruits-icon.svg",
    "items": [
      {
        "id": "fruit-apple",
        "name": "Apple",
        "price": 120,
        "unit": "kg",
        "weight": "1kg",
        "image": "apple.png",
        "inStock": true,
        "qnt": 1,
        "description": "Crisp, sweet, and incredibly juicy apples, perfect for a healthy snack or a delicious pie. Sourced from the finest orchards, they're bursting with natural flavor and essential nutrients.",
        "additionalInfo": "Himachal origin | Store in a cool, dry place or refrigerate for extended freshness. Best consumed within a week of purchase.",
        "isFeatured": true,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fruit-banana",
        "name": "Banana",
        "price": 40,
        "unit": "dozen",
        "weight": "12 pcs",
        "image": "banana.png",
        "inStock": true,
        "qnt": 1,
        "description": "Energy-packed, sweet ripe bananas, ideal for a quick breakfast, smoothies, or baking. These creamy and flavorful bananas are a great source of potassium.",
        "additionalInfo": "Naturally ripened, ensuring optimal sweetness and texture. Store at room temperature; refrigerate once fully ripe to slow further ripening.",
        "isFeatured": false,
        "isNew": true,
        "onSale": true,
        "hasSpecialOffer": true,
        "offerDetails": {
          "type": "discount",
          "value": 10,
          "unit": "%",
          "originalPrice": 45,
          "expires": "2025-07-15"
        }
      },
      {
        "id": "fruit-orange",
        "name": "Orange",
        "price": 80,
        "unit": "kg",
        "weight": "1kg",
        "image": "orange.png",
        "inStock": true,
        "qnt": 1,
        "description": "Zesty and refreshing oranges, loaded with Vitamin C. Perfect for juicing, adding to fruit salads, or simply enjoying fresh. Their vibrant flavor is a delight.",
        "additionalInfo": "No added wax or artificial coatings. Store in a cool, dry place. For maximum juice, bring to room temperature before squeezing.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fruit-mango",
        "name": "Mango",
        "price": 150,
        "unit": "kg",
        "weight": "1kg",
        "image": "mango.png",
        "inStock": true,
        "qnt": 1,
        "description": "Experience the king of fruits with our Alphonso mangoes, renowned for their unparalleled sweetness, rich aroma, and creamy texture. A true tropical delight!",
        "additionalInfo": "Seasonal delicacy, available for a limited time. Naturally ripened for the best flavor. Store at room temperature until ripe, then refrigerate.",
        "isFeatured": true,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fruit-pomegranate",
        "name": "Pomegranate",
        "price": 140,
        "unit": "kg",
        "weight": "1kg",
        "image": "pomegranate.png",
        "inStock": true,
        "qnt": 1,
        "description": "Sweet and juicy pomegranates, brimming with vibrant red arils (seeds). A fantastic source of antioxidants, perfect for snacking, salads, or juicing.",
        "additionalInfo": "Store in a cool, dry place or refrigerate for longer shelf life. Best consumed fresh. Seeds can be frozen for later use.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fruit-papaya",
        "name": "Papaya",
        "price": 45,
        "unit": "kg",
        "weight": "1kg",
        "image": "papaya.png",
        "inStock": true,
        "qnt": 1,
        "description": "Luscious papayas, known for their sweet, buttery flesh and incredible digestive benefits. A versatile fruit, great on its own or in smoothies.",
        "additionalInfo": "Ready to eat when the skin is mostly yellow/orange and slightly soft to the touch. Store at room temperature; refrigerate once cut.",
        "isFeatured": false,
        "isNew": true,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fruit-grapes",
        "name": "Grapes",
        "price": 90,
        "unit": "kg",
        "weight": "1kg",
        "image": "grapes.png",
        "inStock": true,
        "qnt": 1,
        "description": "Sweet, crisp, and seedless green grapes, perfect for a refreshing snack or as an addition to cheese boards. Bursting with natural sugars and hydration.",
        "additionalInfo": "High in antioxidants. Wash thoroughly before consumption. Store in the refrigerator in their original packaging or a perforated bag.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fruit-watermelon",
        "name": "Watermelon",
        "price": 35,
        "unit": "piece",
        "weight": "2-3kg",
        "image": "watermelon.png",
        "inStock": true,
        "qnt": 1,
        "description": "The quintessential summer fruit – refreshing, hydrating, and wonderfully sweet. Our watermelons have a vibrant red flesh, perfect for quenching thirst.",
        "additionalInfo": "Naturally sweet and juicy. Store whole at room temperature for up to a week. Once cut, refrigerate promptly in an airtight container.",
        "isFeatured": false,
        "isNew": false,
        "onSale": true,
        "hasSpecialOffer": true,
        "offerDetails": {
          "type": "fixed_price",
          "value": 30,
          "originalPrice": 35,
          "description": "Summer special price! Enjoy this hydrating treat at a discounted rate."
        }
      },
      {
        "id": "fruit-pineapple",
        "name": "Pineapple",
        "price": 60,
        "unit": "piece",
        "weight": "1.5kg",
        "image": "pineapple.png",
        "inStock": true,
        "qnt": 1,
        "description": "Bring a taste of the tropics home with our sweet and tangy pineapples, packed with Vitamin C and bromelain. Excellent in fruit salads, desserts, or savory dishes.",
        "additionalInfo": "Ready to slice and enjoy. Choose pineapples that are heavy for their size and have a sweet aroma at the base. Store at room temperature until ripe, then refrigerate.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fruit-kiwi",
        "name": "Kiwi",
        "price": 25,
        "unit": "piece",
        "weight": "150g",
        "image": "kiwi.png",
        "inStock": true,
        "qnt": 1,
        "description": "This exotic fruit is a powerhouse of nutrients, offering a unique tart-sweet flavor and vibrant green flesh. Perfect on its own or as a colourful addition to any dish.",
        "additionalInfo": "Imported and carefully selected for quality. Store refrigerated to maintain freshness. Ripen at room temperature with an apple or banana if harder.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      }
    ]
  },
  {
    "id": 2,
    "name": "Vegetables",
    "categoryIcon": "veg-icon.svg",
    "items": [
      {
        "id": "veg-potato",
        "name": "Potato",
        "price": 25,
        "unit": "kg",
        "weight": "1kg",
        "image": "potato.png",
        "inStock": true,
        "qnt": 1,
        "description": "Our versatile staple veggie, perfect for a wide array of Indian recipes from curries to fries. These firm and clean potatoes are essential for every kitchen.",
        "additionalInfo": "Firm, clean, and free from sprouts. Store in a cool, dark, and dry place away from direct sunlight to prevent sprouting and greening.",
        "isFeatured": true,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "veg-onion",
        "name": "Onion",
        "price": 30,
        "unit": "kg",
        "weight": "1kg",
        "image": "onion.png",
        "inStock": true,
        "qnt": 1,
        "description": "Enhance the flavor of any dish with our fresh red onions, known for their pungent taste and crisp texture. A fundamental ingredient in countless cuisines.",
        "additionalInfo": "Excellent shelf life when stored in a cool, dry, well-ventilated area. Avoid refrigeration, which can lead to sogginess.",
        "isFeatured": false,
        "isNew": false,
        "onSale": true,
        "hasSpecialOffer": true,
        "offerDetails": {
          "type": "buy_one_get_one",
          "value": "free_small_pack",
          "description": "Buy 1kg of fresh onions, and get an additional 250g pack absolutely free! Stock up now."
        }
      },
      {
        "id": "veg-tomato",
        "name": "Tomato",
        "price": 35,
        "unit": "kg",
        "weight": "1kg",
        "image": "tomato.png",
        "inStock": true,
        "qnt": 1,
        "description": "Juicy, ripe tomatoes, perfect for adding tang and color to your curries, salads, and sauces. Sourced directly from farms for peak freshness.",
        "additionalInfo": "Farm fresh, ensuring superior taste and quality. Store at room temperature away from direct sunlight; refrigerate only if very ripe to extend life.",
        "isFeatured": false,
        "isNew": true,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "veg-carrot",
        "name": "Carrot",
        "price": 40,
        "unit": "kg",
        "weight": "1kg",
        "image": "carrot.png",
        "inStock": true,
        "qnt": 1,
        "description": "Vibrantly orange carrots, sweet and crunchy, making them great for juicing, salads, or cooking. Packed with essential vitamins and fiber.",
        "additionalInfo": "Naturally sweet and firm. Store in the refrigerator, preferably in a sealed bag or container to retain moisture and crispness.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "veg-capsicum",
        "name": "Capsicum",
        "price": 60,
        "unit": "kg",
        "weight": "1kg",
        "image": "capsicum.png",
        "inStock": true,
        "qnt": 1,
        "description": "Crisp green bell peppers, offering a fresh, slightly bitter flavor perfect for stir-fries, salads, and as a topping for pizzas. A versatile culinary essential.",
        "additionalInfo": "Crisp and fresh, sourced for optimal quality. Store in the vegetable drawer of your refrigerator to maintain firmness and extend shelf life.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "veg-brinjal",
        "name": "Brinjal",
        "price": 30,
        "unit": "kg",
        "weight": "1kg",
        "image": "brinjal.png",
        "inStock": true,
        "qnt": 1,
        "description": "Glossy and tender brinjal (eggplant), ideal for classic Indian dishes like bharta, sambar, or delectable fries. Known for its rich, earthy flavor when cooked.",
        "additionalInfo": "Select firm, glossy, and heavy brinjals for best quality. Store in a cool, dry place; avoid refrigerating for too long as it can get damaged by cold.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "veg-ladyfinger",
        "name": "Lady Finger",
        "price": 45,
        "unit": "kg",
        "weight": "1kg",
        "image": "lady-finger.png",
        "inStock": true,
        "qnt": 1,
        "description": "Also known as Okra or Bhindi, these slim and fresh pods are perfect for a simple stir-fry or delicious curries. Known for their unique texture and mild taste.",
        "additionalInfo": "Ensure pods are tender and snap easily. Store unwashed in a paper bag in the refrigerator; wash just before cooking to prevent sliminess.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "veg-cabbage",
        "name": "Cabbage",
        "price": 25,
        "unit": "piece",
        "weight": "800g",
        "image": "cabbage.png",
        "inStock": true,
        "qnt": 1,
        "description": "Crisp, round, and fresh cabbage, a staple for salads, stir-fries, and traditional Indian sabzis. Offers a mild, slightly sweet flavor when cooked.",
        "additionalInfo": "Locally grown and harvested fresh. Store whole in the refrigerator, wrapped loosely or in a crisper drawer to maintain freshness.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "veg-cauliflower",
        "name": "Cauliflower",
        "price": 35,
        "unit": "piece",
        "weight": "900g",
        "image": "cauliflower.png",
        "inStock": true,
        "qnt": 1,
        "description": "Versatile and nutritious cauliflower, perfect for classic gobi parathas, flavorful curries, or roasting. Its florets offer a mild, slightly nutty taste.",
        "additionalInfo": "Clean, compact, and pesticide-free. Store in the refrigerator, preferably stem down, to prevent moisture accumulation and spoilage.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "veg-beans",
        "name": "Beans",
        "price": 50,
        "unit": "kg",
        "weight": "1kg",
        "image": "beans.png",
        "inStock": true,
        "qnt": 1,
        "description": "Tender green beans, a rich source of fiber and essential vitamins. Excellent steamed, stir-fried, or added to mixed vegetable curries. Fresh harvest guaranteed.",
        "additionalInfo": "Fresh harvest, ensuring maximum crunch and flavor. Store unwashed in a plastic bag or container in the crisper drawer of your refrigerator.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      }
    ]
  },
  {
    "id": 3,
    "name": "Fish",
    "categoryIcon": "fish-icon.svg",
    "items": [
      {
        "id": "fish-rohu",
        "name": "Rohu",
        "price": 260,
        "unit": "kg",
        "weight": "1kg",
        "image": "rohu.png",
        "inStock": true,
        "qnt": 1,
        "description": "Premium freshwater Rohu, known for its delicate texture and mild flavor. Expertly cleaned and precisely cut, ready for your favorite curry or fry.",
        "additionalInfo": "Sourced from daily catch, ensuring utmost freshness. Store in the coldest part of your refrigerator and consume within 24 hours for best quality.",
        "isFeatured": true,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fish-katla",
        "name": "Katla",
        "price": 270,
        "unit": "kg",
        "weight": "1kg",
        "image": "katla.png",
        "inStock": true,
        "qnt": 1,
        "description": "A classic Bengali-style fish, Katla is prized for its firm, flaky flesh and rich taste. Perfect for traditional preparations or a simple fish fry.",
        "additionalInfo": "Available as whole fish or precisely sliced pieces. Ensure quick cooking after purchase for optimal taste. Ideal for curries and deep frying.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fish-prawn",
        "name": "Prawns (Medium)",
        "price": 480,
        "unit": "kg",
        "weight": "500g",
        "image": "prawns.png",
        "inStock": true,
        "qnt": 1,
        "description": "Succulent medium-sized prawns, meticulously cleaned and deveined, ready to transform into a delicious curry, stir-fry, or grilled delicacy. A versatile seafood choice.",
        "additionalInfo": "Freshly deveined and ready to cook, saving you preparation time. Store in the coldest part of the refrigerator or freeze for longer storage.",
        "isFeatured": false,
        "isNew": false,
        "onSale": true,
        "hasSpecialOffer": true,
        "offerDetails": {
          "type": "percentage_discount",
          "value": 15,
          "originalPrice": 565,
          "description": "Limited time offer! Grab 15% off on medium prawns. Perfect for your next seafood feast."
        }
      },
      {
        "id": "fish-hilsa",
        "name": "Hilsa (Ilish)",
        "price": 1200,
        "unit": "kg",
        "weight": "1kg",
        "image": "hilsa.png",
        "inStock": true,
        "qnt": 1,
        "description": "Experience the incomparable flavor of premium Hilsa, a seasonal river fish revered for its distinctive aroma and exceptionally rich, oily flesh. A true delicacy.",
        "additionalInfo": "Seasonal delicacy, highly sought after for its unique taste. Best enjoyed steamed, fried, or in traditional Bengali preparations. Handle with care due to fine bones.",
        "isFeatured": false,
        "isNew": true,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fish-pomfret",
        "name": "Pomfret",
        "price": 600,
        "unit": "kg",
        "weight": "1kg",
        "image": "pomfret.png",
        "inStock": true,
        "qnt": 1,
        "description": "Our fresh Pomfret boasts delicate white flesh and a mild, subtly sweet flavor, making it a favorite for grilling, frying, or baking. A versatile sea fish.",
        "additionalInfo": "Finest quality sea fish, known for its less bony structure. Ideal for whole fish preparations. Consume fresh for the best culinary experience.",
        "isFeatured": true,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fish-basa",
        "name": "Basa Fillet",
        "price": 350,
        "unit": "kg",
        "weight": "500g",
        "image": "basa-fillet.png",
        "inStock": true,
        "qnt": 1,
        "description": "Convenient and boneless Basa fillets, perfect for quick and easy meals. Its mild flavor and tender texture make it a great choice for various cooking methods.",
        "additionalInfo": "Quick-frozen to lock in freshness and nutrients. Thaw completely before cooking. Ideal for baking, pan-frying, or adding to curries.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fish-tilapia",
        "name": "Tilapia",
        "price": 220,
        "unit": "kg",
        "weight": "1kg",
        "image": "tilapia.png",
        "inStock": true,
        "qnt": 1,
        "description": "Fresh Tilapia with a mild, slightly sweet flavor and flaky texture. A lean and healthy fish, excellent for grilling, baking, or pan-searing.",
        "additionalInfo": "Whole fish, cleaned and scaled. Great for diverse recipes. Store chilled and cook soon after purchase.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fish-mackerel",
        "name": "Mackerel (Bangda)",
        "price": 200,
        "unit": "kg",
        "weight": "1kg",
        "image": "mackerel.png",
        "inStock": true,
        "qnt": 1,
        "description": "Popular in South Indian cuisine, Mackerel (Bangda) is known for its distinctive flavor and high Omega-3 fatty acid content. Perfect for frying or curries.",
        "additionalInfo": "Rich in Omega-3 fatty acids, making it a healthy choice. Best enjoyed fresh. Consume promptly or freeze for later use.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fish-sardine",
        "name": "Sardine (Pedvey)",
        "price": 150,
        "unit": "kg",
        "weight": "1kg",
        "image": "sardine.png",
        "inStock": true,
        "qnt": 1,
        "description": "Small, oily fish packed with immense nutrition, especially Omega-3s. Sardines (Pedvey) are incredibly flavorful, especially when pan-fried until crispy.",
        "additionalInfo": "Best fried or grilled. A highly nutritious and affordable seafood option. Consume fresh for optimal taste and health benefits.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "fish-snapper",
        "name": "Red Snapper",
        "price": 550,
        "unit": "kg",
        "weight": "1kg",
        "image": "red-snapper.png",
        "inStock": true,
        "qnt": 1,
        "description": "A premium fish with firm texture and a delicate, slightly sweet taste. Red Snapper is highly versatile, excellent for baking whole, grilling fillets, or pan-searing.",
        "additionalInfo": "Premium quality sea fish, ideal for special meals. Its robust flesh holds up well to various cooking methods. Ensure proper refrigeration.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      }
    ]
  },
  {
    "id": 4,
    "name": "Meat",
    "categoryIcon": "meat-icon.svg",
    "items": [
      {
        "id": "meat-chicken",
        "name": "Chicken Curry Cut",
        "price": 220,
        "unit": "kg",
        "weight": "1kg",
        "image": "pureChicken.png",
        "inStock": true,
        "qnt": 1,
        "description": "Freshly cut, tender pieces of chicken, perfectly sized for rich and flavorful home-style curries. Our chicken is sourced for quality and taste.",
        "additionalInfo": "Halal certified and meticulously cleaned for your convenience. Best consumed fresh or frozen immediately for later use.",
        "isFeatured": true,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "meat-chicken-breast",
        "name": "Chicken Breast Boneless",
        "price": 280,
        "unit": "kg",
        "weight": "500g",
        "image": "chicken-breast.png",
        "inStock": true,
        "qnt": 1,
        "description": "Lean, boneless, and protein-rich chicken breast, ideal for grilling, stir-fries, or healthy salads. A versatile cut for a balanced diet.",
        "additionalInfo": "Skinless and trimmed for ready use. Store in refrigeration and use within 2 days, or freeze for longer preservation.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "meat-mutton",
        "name": "Goat Mutton",
        "price": 750,
        "unit": "kg",
        "weight": "500g",
        "image": "goat-mutton.png",
        "inStock": true,
        "qnt": 1,
        "description": "Savor the rich, distinct flavor of premium goat mutton, cut into juicy and tender pieces. Perfect for traditional curries and slow-cooked delights.",
        "additionalInfo": "Sourced from farm-raised goats, ensuring ethical practices and superior taste. Marinate for enhanced tenderness and flavor.",
        "isFeatured": false,
        "isNew": false,
        "onSale": true,
        "hasSpecialOffer": true,
        "offerDetails": {
          "type": "percentage_discount",
          "value": 10,
          "originalPrice": 833.33,
          "description": "Enjoy 10% off on your first purchase of premium goat mutton! A perfect introduction to quality meat."
        }
      },
      {
        "id": "meat-mutton-keema",
        "name": "Mutton Keema",
        "price": 800,
        "unit": "kg",
        "weight": "500g",
        "image": "mutton-keema.png",
        "inStock": true,
        "qnt": 1,
        "description": "Finely ground goat meat, Mutton Keema is incredibly versatile and perfect for crafting delicious kebabs, savory keema curries, or rich pasta sauces.",
        "additionalInfo": "Fine ground for consistent texture and quick cooking. Ideal for Indian and Mediterranean dishes. Store chilled or freeze immediately.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "meat-duck",
        "name": "Duck Meat",
        "price": 480,
        "unit": "kg",
        "weight": "1kg",
        "image": "duck-meat.png",
        "inStock": true,
        "qnt": 1,
        "description": "Experience the rich, robust taste of duck meat, ideal for hearty roasts, flavorful curries, or confit. Known for its distinct flavor and tender texture.",
        "additionalInfo": "Sourced from country-style farms, ensuring authentic taste. Best when slow-cooked to bring out its full flavor and tenderness.",
        "isFeatured": false,
        "isNew": true,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "meat-liver",
        "name": "Chicken Liver",
        "price": 150,
        "unit": "kg",
        "weight": "500g",
        "image": "chicken-liver.png",
        "inStock": true,
        "qnt": 1,
        "description": "Nutrient-dense and incredibly soft chicken liver, a rich source of iron and vitamins. Perfect for a quick fry, pâté, or adding to curries for depth of flavor.",
        "additionalInfo": "Freshly cut and hygienically packed. Best consumed fresh or frozen promptly. Great for boosting iron intake.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "meat-wings",
        "name": "Chicken Wings",
        "price": 200,
        "unit": "kg",
        "weight": "1kg",
        "image": "chicken-wings.png",
        "inStock": true,
        "qnt": 1,
        "description": "Juicy chicken wings, the ultimate crowd-pleaser for grills, deep-fries, or baking with your favorite sauce. Perfect for game nights and gatherings.",
        "additionalInfo": "Ready to marinate and cook. Comes with skin for extra crispiness. Ideal for appetizers or a hearty snack.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "meat-drumstick",
        "name": "Chicken Drumstick",
        "price": 250,
        "unit": "kg",
        "weight": "1kg",
        "image": "chicken-drumstick.png",
        "inStock": true,
        "qnt": 1,
        "description": "Tender and succulent chicken drumsticks, perfect for tandoori preparations, grilling, or rich curries. Their juicy meat stays moist during cooking.",
        "additionalInfo": "Comes with skin, which helps retain moisture and flavor during cooking. Great for barbecues and roasted dishes.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "meat-biryani-cut",
        "name": "Biryani Cut Chicken",
        "price": 230,
        "unit": "kg",
        "weight": "1kg",
        "image": "biryani-cut-chicken.png",
        "inStock": true,
        "qnt": 1,
        "description": "Specially cut large chicken pieces (thigh and leg mix), designed to absorb flavors beautifully, making them ideal for authentic and aromatic biryanis.",
        "additionalInfo": "Perfect mix of thigh and leg pieces, ensuring tender and flavorful meat in every bite of biryani. Marinate well for best results.",
        "isFeatured": false,
        "isNew": false,
        "onSale": false,
        "offerDetails": null
      },
      {
        "id": "meat-boneless-mutton",
        "name": "Boneless Mutton",
        "price": 950,
        "unit": "kg",
        "weight": "500g",
        "image": "boneless-mutton.png",
        "inStock": true,
        "qnt": 1,
        "description": "Tender boneless mutton cubes, perfect for hassle-free curries, stews, or kebabs. Enjoy the rich taste of premium goat meat without any bones.",
        "additionalInfo": "Soft cut, ideal for quick cooking in curries and braises. Marinate well to enhance tenderness. Versatile for a variety of international dishes.",
        "isFeatured": true,
        "isNew": false,
        "onSale": true,
        "hasSpecialOffer": true,
        "offerDetails": {
          "type": "combo_deal",
          "value": "Buy 2, Get 10% Off",
          "description": "Perfect for family dinners! Buy two packs of boneless mutton and receive a 10% discount on your total order.",
          "minimumQuantity": 2,
          "discountPercentage": 10
        }
      }
    ]
  }
]
};